### ISSUE TITLE
NPM Buildpack should only run "npm install"

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/npm-install#109]
As per the [Node.js re-architecture RFC](https://github.com/paketo-buildpacks/nodejs/blob/main/rfcs/0001-buildpacks-architecture.md), once https://github.com/paketo-buildpacks/nodejs/issues/212 is implemented, we should **rename** this buildpack to **Paketo NPM Install Buildpack** and update the buildpack to only run `npm install`. After this is complete, Language family ordering will look like:
```
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"

  [[order.group]]
    id = "paketo-buildpacks/yarn"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"

  [[order.group]]
    id = "paketo-buildpacks/tini"

  [[order.group]]
    id = "paketo-buildpacks/yarn-start"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"

  [[order.group]]
    id = "paketo-buildpacks/tini"

  [[order.group]]
    id = "paketo-buildpacks/npm-start"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
```

**Comment by arjun024** [comment]
Due to [RFC 0002](https://github.com/paketo-buildpacks/nodejs/blob/d0389301eaf1372968ea73df23758e8607a32b27/rfcs/0002-remove-tini.md), tini has been removed from the group. See https://github.com/paketo-buildpacks/nodejs/pull/241
