### ISSUE TITLE
NPM buildpack should allow users to force which npm command runs

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/npm-install#122]
Currently, the install command that the NPM buildpack runs depends on which files are present in an application's source code. Either `npm install` `npm ci` or `npm rebuild` will be used. 

We have seen a case where the angular CLI is not properly installed in an app container because the NPM buildpack runs `npm ci` instead of `npm install`. A workaround was to remove the `package-lock.json` from the app's source code. This caused the buildpack to run `npm install`, and resolved the problem.

But removing a `package-lock.json` from source code is not a great long-term solution because it prevents developers from locking their node modules to specific versions.

There should be a way (perhaps via an environment variable set at container build time) for developers to specify which `npm` installation command the buildpack should run.

**Comment by ryanmoran** [comment]
After further investigation of the situation, I believe that this scenario is covered by #132. In this case, the developers had not updated their `package-lock.json` when they made changes to their `package.json`. This resulted in a subsequent build reusing the `node_modules` layer as it detected no changes to the `package-lock.json` and then not installing the newly updated dependency. The buildpack should be capable of detecting this situation and error in this case. If that is possible, then it may not make sense to introduce a command override just yet.

**Comment by ryanmoran** [comment]
Do we still feel like this is an unmet user need? If not, should we close this?

**Comment by thitch97** [comment]
I think it makes sense to opt for the changes outlined in #132. Since the buildpack is already capable of deciding between the commands, I think it's reasonable to simply ensure users' apps are set up correctly instead of introducing a configuration option they may not know how to utilize correctly.

**Comment by arjun024** [comment]
Closing.
@fg-j If you encounter cases that would not be solved by #132, feel free to reopen.
