### ISSUE TITLE
Apps that use ng build fail to start with "build Module not found: Error: Recursion in resolving"

### ISSUE THREAD

**Issue by floragj** [paketo-buildpacks/npm-install#123]
Application containers that have been built with the NPM buildpack **and** use the `ng build` command face the error: `
Module not found: Error: Recursion in resolving` **when using Angular 10**. [This issue filed for the angular-cli](https://github.com/angular/angular-cli/issues/18021) indicates that the issue can be caused by the `node_modules` directory containing symlinks.

The NPM buildpack [creates a symlink](https://github.com/paketo-buildpacks/npm/blob/88eaea194b8ae75693a2ec4c100c8237da3cce96/install_build_process.go#L36) for the `node_modules` directory during its install process. This seems to be the root cause of the error.

Developers can work around the issue by adding the following to the `angular.json` file in the application source directory:
```
{
"architect" : {
  "build" : {
    "options" : {
      "preserveSymlinks" : true
   }
  }
 } 
}
```

This workaround should be documented or the buildpack should address this problem itself.

**Comment by arjun024** [comment]
> The NPM buildpack creates a symlink for the node_modules directory during its install process. This seems to be the root cause of the error.

The buildpack does not create symlinks inside the `node_modules`. It symlinks the `node_modules` directory from app -> a_reusable_layer. From the angular-cli issue description, the issue causes when `node_modules` directory **contain** symlinks and angular creates symlinks in its `node_modules` dir. So hypothetically even if the `node_modules` weren't a symlink, this issue would still persist. Looks like an angular problem not a buildpack problem?

**Comment by ryanmoran** [comment]
As this is believed to be an issue with a specific `npm` package, should this issue be closed?
