### ISSUE TITLE
node_modules should be rebuilt if version of node changes between builds

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/npm-install#153]
## What happened?
Similar to paketo-buildpacks/yarn-install#144, buildpack reuses cached version of `node_modules` even when version of node has changed between builds. For apps with native extensions, this can cause failures at runtime though the build succeeds.

## Reproduction Steps
Using
```
 ‣ pack --version
0.13.1+git-4134cc6.build-1135
```
1. Clone [this sample app](https://github.com/fg-j/native-extensions-sample) `git@github.com:fg-j/native-extensions-sample.git`
1. Build the app (and force the cache to be cleared) `pack build with-bcrypt -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.20-base --clear-cache`
1. Run the app `docker run -d --env PORT=8080 --publish 8080:8080 with-bcrypt`
1. Curl the app endpoint `curl 0.0.0.0:8080`. Expected output is: `Hello, World!`
1. Update the desired version of node by changing `buildpack.yml` to:
```
---
nodejs:
  version: ^14.0.0
```
1. Rebuild the app (but don't force the cache to be cleared) `pack build with-bcrypt -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.20-base` The output should contain:
```
[builder] Paketo Node Engine Buildpack 0.1.2
[builder]   Resolving Node Engine version
[builder]     Candidate version sources (in priority order):
[builder]       buildpack.yml -> "^14.0.0"
[builder]                     -> ""
[builder]       <unknown>     -> "*"
[builder]
[builder]     Selected Node Engine version (using buildpack.yml): 14.13.0
...
...
...
[builder] Paketo NPM Install Buildpack 0.2.1
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       node_modules      -> "Not found"
[builder]       npm-cache         -> "Not found"
[builder]       package-lock.json -> "Found"
[builder]
[builder]     Selected NPM build process: 'npm ci'
[builder]
[builder]   Reusing cached layer /layers/paketo-buildpacks_npm-install/modules
```
This indicates that the cached version of the `node_modules` has been reused, rather than rebuilding for the new node version.
1. Stop the previously running instance of the app (e.g. `docker stop 83e251bd0c449a7fbfea20b742ffd5b4b5dbf885307e3c26da0a0c8d7a647254`)
1. Run the newly built version of the app: `docker run -d --env PORT=8080 --publish 8080:8080 with-bcrypt`
1. Curl the app endpoint `curl 0.0.0.0:8080`. Desired output is: `Hello, World!` but actual output is:
```
curl: (7) Failed to connect to 0.0.0.0 port 8080: Connection refused
```
1. Get logs for the container (e.g. `docker logs f025c0b9c318`) Expected output:
```
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/layers/paketo-buildpacks_npm-install/modules/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/layers/paketo-buildpacks_npm-install/modules/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
```

This shows that the app fails to run as expected because bcrypt was compiled with a different version of node than the one that is installed in the app container.

## Checklist

Please confirm the following:

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by ForestEckhardt** [comment]
I was casually checking this out and found the `npm config list` command as a way to potentially conveniently cache the NPM configuration, which includes the node version in some way.

**Comment by andymoe** [comment]
I'll give this a go.

**Comment by andymoe** [comment]
This just took way longer to get to than I wanted. I'm out the rest of the week and there are still unit tests to fix (unfortunately we need some magic numbers right now) I'm not going to get to them before I leave tomorrow morning. Happy to finish up when I get back but if anyone is itching to get this done here is the brach that needs attention: https://github.com/andymoe/npm-install/tree/rebuild-on-node-version-change_153
