### ISSUE TITLE
There's no way to clean up node_modules after building

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/npm-install#170]
Some users may want to have their `node_modules` removed after generating some set of static assets akin to the [source removal](https://vmware.slack.com/archives/CUR2H2KFE/p1608311539105800) concept in the Go buildpack. Perhaps we should consider allowing users to opt-in to this workflow for the Node.js buildpack family as well.

**Comment by arjun024** [comment]
See a user discussion regarding this: https://paketobuildpacks.slack.com/archives/CUD6R3CPL/p1612338123000800?thread_ts=1608826963.002200&cid=CUD6R3CPL

This feature should probably include the ability to clean up user supplied directories (e.g. `src`)

**Comment by th3n3rd** [comment]
A common scenario: trying to build and serve a frontend application (i.e. React, Angular).

Ideally the build should use the nodejs buildpack as well as nginx to serve the app.

When the application is built it will need npm installed dependencies, but for it's run image we only need the static content served by nginx.

The current images built with both buildpacks now have the huge disadvantage of being heavy for absolutely no benefit. In my current project we have a 1.2GB image, where 1GB is just unused node_modules.

It would be nice if the layer persistence could be switched off.

**Comment by mhdawson** [comment]
I noticed the suggest to use the source-removal buildpack in https://github.com/paketo-buildpacks/nodejs/issues/650#issuecomment-1285799375

Just though I'd mention in case that would work for this use case as well.

**Comment by ryanmoran** [comment]
I think this specific case is really better served by the [Web Servers buildpack](https://github.com/paketo-buildpacks/web-servers/). Its designed to handle frontend applications like this and only has `node_modules` available during the build phase.

For any other case, using the `source-removal` buildpack would probably be the best route.

I'm gonna close this as we don't plan to do anything about this in the Node.js buildpack at this time.
