### ISSUE TITLE
How do I exclude local 'node_modules' folder from the build ?

### ISSUE THREAD

**Issue by bmoussaud** [paketo-buildpacks/npm-install#256]
## What happened?
I run the following command at the root of my angular project `pack build myapp-gui --buildpack gcr.io/paketo-buildpacks/nodejs` that fails with the following dump

```
[builder] Paketo NPM Install Buildpack 0.4.0
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       node_modules      -> "Found"
[builder]       npm-cache         -> "Not found"
[builder]       package-lock.json -> "Found"
[builder]
[builder]     Selected NPM build process: 'npm rebuild'
[builder]
[builder]   Executing build process
[builder] vendored node_modules have unmet dependencies: npm list failed: exit status 1
[builder]     npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
[builder]     myapp-gui@0.0.0 /workspace
[builder]     +-- UNMET DEPENDENCY @angular/animations@12.1.2
[builder]     | `-- UNMET DEPENDENCY tslib@2.3.0
[builder]     +-- UNMET DEPENDENCY @angular/common@12.1.2
[builder]     | `-- UNMET DEPENDENCY tslib@2.3.0
[builder]     +-- UNMET DEPENDENCY @angular/compiler@12.1.2
[builder]     | `-- UNMET DEPENDENCY tslib@2.3.0
[builder]     +-- UNMET DEPENDENCY @angular/core@12.1.2
```

* What were you attempting to do?

after spending few hours understanding the cryptic error, I finally got it: I build my project locally using vscode and the `ng build` and the `node_modules` directory  has been created locally, mistaking the buildpack that expected to run `npm rebuild`

* What did you expect to happen?

* What was the actual behavior? Please provide log output, if possible.
as soon as I removed it, I finally succeeded to build my image.

but the dev experience is weak, I can use the ng serve without having a conflict with the build of the image using the buildpack. So I'm wondering if there is an option to exclude folders from the build process or other configuration tips to not include folders into the build process.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

```
pack version
0.19.0+git-360dbae.build-2550
```

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
You can use a `project.toml` file to specify the files to include or exclude in the build. Check out the docs for that here: https://buildpacks.io/docs/app-developer-guide/using-project-descriptor/.

**Comment by bmoussaud** [comment]
@ryanmoran  thank you. it works perfectly.
