### ISSUE TITLE
We should document the npmrc binding

### ISSUE THREAD

**Issue by loewenstein** [paketo-buildpacks/npm-install#316]
I am not sure if this is a generally followed convention in the Paketo project, but I like the fact that e.g. the maven buildpack documents the supported bindings in the [README.md](https://github.com/paketo-buildpacks/maven#bindings) and would appreciate, if the npm install buildpack could do the same.

**Comment by ryanmoran** [comment]
We've got these two issues to track this:
* https://github.com/paketo-buildpacks/paketo-website/issues/397
* https://github.com/paketo-buildpacks/paketo-website/issues/391

**Comment by loewenstein** [comment]
OK, got it. I actually like that the maven buildpack does document config and bindings in github, but having it documented is much more important than where and this should probably anyway be documented on Paketo.io.

Hence, if you prefer to close this I'd be understanding.
