### ISSUE TITLE
exec.d file needs to be checked to during rebuild

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/npm-install#342]
During a rebuild the buildpack blindly assumes that the exec.d file in the buildpack has not changed between builds. This could lead to potentially incorrect rebuild behavior when the buildpack reuses the old layer with a stale exec.d process. We should verify that the exec.d process is the same on rebuild.

**Comment by mhdawson** [comment]
@ForestEckhardt do you believe that https://github.com/paketo-buildpacks/npm-install/pull/393 fixed this issue? It's mentioned that it might have?

**Comment by ForestEckhardt** [comment]
That seems about right. Thanks!
