### ISSUE TITLE
build fails when using npm workspaces and `node_modules` is required during build and launch

### ISSUE THREAD

**Issue by pbusko** [paketo-buildpacks/npm-install#498]
## Expected Behavior

build should succeed, when using project with npm workspaces and `node_modules` are required at both `build` and `launch`.

## Current Behavior

build fails during the `Executing launch environment install process` phase:

```
            [builder]   Executing build environment install process
            [builder]     Running 'npm install --unsafe-perm --cache /layers/paketo-buildpacks_npm-install/npm-cache'
            [builder]       
            [builder]       added 167 packages, and audited 169 packages in 12s
            [builder]       
            [builder]       56 packages are looking for funding
            [builder]         run `npm fund` for details
            [builder]       
            [builder]       found 0 vulnerabilities
            [builder]       npm notice 
            [builder]       npm notice New minor version of npm available! 9.5.1 -> 9.6.5
            [builder]       npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.5>
            [builder]       npm notice Run `npm install -g npm@9.6.5` to update!
            [builder]       npm notice 
            [builder]       Completed in 12.345s
            [builder] 
            [builder]   Configuring build environment
            [builder]     NODE_ENV -> "development"
            [builder]     PATH     -> "$PATH:/layers/paketo-buildpacks_npm-install/build-modules/node_modules/.bin"
            [builder] 
            [builder]   Generating SBOM for /layers/paketo-buildpacks_npm-install/build-modules
            [builder]       Completed in 344ms
            [builder] 
            [builder]   Executing launch environment install process
            [builder]     Running 'npm prune'
            [builder]       
            [builder]       changed 1 package, and audited 4 packages in 827ms
            [builder]       
            [builder]       found 0 vulnerabilities
            [builder] failed to copy linked module directory to layer path: failed to copy: destination exists: remove /layers/paketo-buildpacks_npm-install/build-modules/src/packages/hello-world: directory not empty
            [builder] ERROR: failed to build: exit status 1
```

From what we can see, there are currently several issues with the workspace handling:

1. When required at both build and launch, the call to the `symlinkerResolver.Resolve` inside the `if launch` block is done with the same set of parameters, as within the `if build` block.
  After the first call, the source folder no longer exists (it gets deleted by `linker.Link()` function). Also, the target folder is already present in the `build-modules` layer

https://github.com/paketo-buildpacks/npm-install/blob/56c83121be52918034dc2c830ec9f609072fc408/build.go#L142-L145
https://github.com/paketo-buildpacks/npm-install/blob/56c83121be52918034dc2c830ec9f609072fc408/build.go#L242
https://github.com/paketo-buildpacks/npm-install/blob/56c83121be52918034dc2c830ec9f609072fc408/build.go#L252-L255

2. workspace modules are not copied from the build layer to the launch layer
3. in the produced image, workspace modules in the `projectPath` are pointing to nonexistent directory in the `/tmp` folder, `create-symlinks` helper manages only symlink to the `node_modules` folder. 

## Steps to Reproduce

1. Add `build = true` here: https://github.com/paketo-buildpacks/npm-install/blob/56c83121be52918034dc2c830ec9f609072fc408/integration/testdata/workspaces/commonjs/plan.toml#L10-L11
4. Run integration tests

**Comment by jansu76** [comment]
Not sure if this failure is related, or caused by issues with how workspaces are handled in npm-install https://github.com/paketo-buildpacks/node-run-script/issues/230

**Comment by jansu76** [comment]
Also this one was related to workspaces, fixed / changed in 1.1.0: https://github.com/paketo-buildpacks/npm-install/issues/492

**Comment by thitch97** [comment]
This has not yet been resolved. I'm currently finishing up a PR to resolve it.

**Comment by jansu76** [comment]
> Are you sure? I can still reproduce this with `1.1.1` and the steps provided above. We didn't have the problem with `1.0.6`. I think that was introduced with workspaces.

No I was just being unclear. I simply meant that the fix https://github.com/paketo-buildpacks/npm-install/issues/492 did change something in relation to workspace handling, and might be worth looking into.
